name: Create issues across prods and levels 

on:
    push:

jobs:
    create-new-issue:
       runs-on: ubuntu-latest
       steps:
       - run: |
            curl -X POST \
            -H "Authorization: Bearer ${{ secrets.MY_REPO_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/xjg2010go/common/dispatches" \
            -d '{"event_type":"level_updated",
                "client_payload":{"levels":["dev1","test1"]}}'