name: Create issues across prods and levels 

on:
    push:

jobs:
    create-new-issue:
        strategy:
            matrix:
                prod: [ prod1, prod2 ]
                level: [ dev, stage, rel ]
        
        uses: xjg2010go/common/.github/workflows/create-issue.yml@main
        secrets: 
            token: ${{ secrets.MY_REPO_SECRET }}
        with:
            title: "${{ matrix.prod }} issue"
            body: "Update for ${{ matrix.level }}"
    
    report-issue-number:
        runs-on: ubuntu-latest 
        needs: create-new-issue 
        steps:
            - run: echo ${{ needs.create-new-issue.outputs.issue-num }}