name: create-repo-issue3

on:
    workflow_call:
        secrets:
          token:
            required: true
        inputs:
            title:
                description: 'Issue title'
                required: true
                type: string
            body:
                description: 'Issue body'
                required: true
                type: string

jobs:
    create-issue:
        runs-on: ubuntu-latest
        outputs:
            inum: ${{ steps.new-issue.outputs.inum }}
        permissions:
            issues: write
        steps:
            - name: Create issue using REST API 
              id: new-issue 
              run: |
                    a=${{ secrets.PAT }}
                    echo $a
                    response=$(curl -L -X POST \
                        -H "Accept: application/vnd.github+json" \
                        -H 'Authorization: Bearer ${{ secrets.PAT }}' \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/repos/xjg2010go/common/issues \
                        --data '{
                           "title": "${{ inputs.title }}",
                           "body": "${{ inputs.body }}"
                          }' \
                        --fail | jq '.number') 
                        echo "inum=$response" >> $GITHUB_OUTPUT