name: Create demo issue 3

on:
    push:

jobs:
    msg:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Simple workflow"
    create-new-issue:
        uses: xjg2010go/common/.github/workflows/create-issue.yml@main
        secrets: inherit 
        with:
            title: "Test issue"
            body: "Test body"
