name: Create demo issue 3

on:
    push:

jobs:
    create-new-issue:
        uses: xjg2010go/common/.github/workflows/create-issue.yml@v1
        secrets: inherit 
        with:
            title: 'Test issue'
            body: 'Test body'
    report-issue-number:
        runs-on: ubuntu-latest
        needs: create-new-issue 
        steps:
            - run: echo ${{ needs.create-new-issue.outputs.issue-num }}