name: Create demo issue

on:
  push:

jobs:
  msg:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SHA of my secret: $(echo -n "${{ secrets.MY_REPO_SECRET }}" | sha256sum)"
    
  issue:
    uses: xjg2010go/common/.github/workflows/create-issue.yml@main
    secrets: 
       token: ${{ secrets.MY_REPO_SECRET }}
    with:
      title: "Test issue"
      body: "Test body"